### ISSUE TITLE
error , please help

### ISSUE THREAD

**Issue by ZarinNegah** [txthinking/brook-manager#6]
brook-manager --listen 127.0.0.1:8080 --ui default --mysqladdress 127.0.0.1:3306 --mysqlusername root --mysqlpassword 111111 --mysqldbname brook
INFO connecting 127.0.0.1:3306
error: Uncaught (in promise) ConnectionRefused: Connection refused (os error 111)
    at async Object.connect (deno:ext/net/01_net.js:333:17)
    at async PoolConnection._connect (https://deno.land/x/mysql@v2.10.2/src/connection.ts:44:35)
    at async PoolConnection.connect (https://deno.land/x/mysql@v2.10.2/src/connection.ts:113:9)
    at async Client.createConnection (https://deno.land/x/mysql@v2.10.2/src/client.ts:11:9)
    at async DeferredStack.creator (https://deno.land/x/mysql@v2.10.2/src/pool.ts:48:26)
    at async DeferredStack.pop (https://deno.land/x/mysql@v2.10.2/src/deferred.ts:29:24)
    at async ConnectionPool.pop (https://deno.land/x/mysql@v2.10.2/src/pool.ts:77:20)
    at async Client.useConnection (https://deno.land/x/mysql@v2.10.2/src/client.ts:57:28)
    at async Client.execute (https://deno.land/x/mysql@v2.10.2/src/client.ts:49:16)
    at async mysql (https://raw.githubusercontent.com/txthinking/denolib/master/mysql.js:78:5)

**Comment by txthinking** [comment]
ask your mysql
